"""
Quantizes the trained float32 weights to Q16.16 fixed-point integers,
verifies the quantized (integer-only) forward pass still matches the
float model's predictions, then generates a C header with everything
the kernel-side inference program needs: weights, biases, and a small
set of labeled test images, all as plain int32 arrays.
"""
import numpy as np

data = np.load("model.npz")
W1, b1, W2, b2 = data["W1"], data["b1"], data["W2"], data["b2"]
X_test, y_test = data["X_test"], data["y_test"]

INPUT_SIZE, HIDDEN_SIZE = W1.shape
_, OUTPUT_SIZE = W2.shape

SHIFT = 16
SCALE = 1 << SHIFT

def to_fixed(arr):
    return np.round(arr * SCALE).astype(np.int64).astype(np.int32)

W1_fx = to_fixed(W1)
b1_fx = to_fixed(b1)
W2_fx = to_fixed(W2)
b2_fx = to_fixed(b2)

# Verify the integer-only quantized forward pass matches the C implementation.
def fixed_forward(x_fx, W1_fx, b1_fx, W2_fx, b2_fx):
    hidden = np.zeros(HIDDEN_SIZE, dtype=np.int64)
    for h in range(HIDDEN_SIZE):
        acc = np.int64(0)
        for i in range(INPUT_SIZE):
            acc += np.int64(x_fx[i]) * np.int64(W1_fx[i, h])
        acc = (acc >> SHIFT) + b1_fx[h]
        hidden[h] = max(0, acc)  # ReLU

    out = np.zeros(OUTPUT_SIZE, dtype=np.int64)
    for o in range(OUTPUT_SIZE):
        acc = np.int64(0)
        for h in range(HIDDEN_SIZE):
            acc += np.int64(hidden[h]) * np.int64(W2_fx[h, o])
        acc = (acc >> SHIFT) + b2_fx[o]
        out[o] = acc

    return int(np.argmax(out))

correct = 0
for i in range(len(X_test)):
    x_fx = to_fixed(X_test[i])
    pred = fixed_forward(x_fx, W1_fx, b1_fx, W2_fx, b2_fx)
    if pred == y_test[i]:
        correct += 1

print(f"Quantized (fixed-point) test accuracy: {correct}/{len(X_test)} = {correct/len(X_test):.4f}")

# Pick one correctly-classified, held-out test image per digit for the demo
chosen_images = []
chosen_labels = []
for digit in range(10):
    for i in range(len(X_test)):
        if y_test[i] == digit:
            x_fx = to_fixed(X_test[i])
            if fixed_forward(x_fx, W1_fx, b1_fx, W2_fx, b2_fx) == digit:
                chosen_images.append(to_fixed(X_test[i]))
                chosen_labels.append(digit)
                break

print(f"Selected {len(chosen_images)} demo images (one per digit, all correctly classified)")

# --- Generate the C header ---
def c_array(name, arr, per_line=12):
    flat = np.asarray(arr).flatten()
    lines = []
    for i in range(0, len(flat), per_line):
        chunk = flat[i:i+per_line]
        lines.append("    " + ", ".join(str(int(v)) for v in chunk) + ",")
    body = "\n".join(lines)
    return f"static const int32_t {name}[] = {{\n{body}\n}};\n"

with open("../userspace/model_data.h", "w") as f:
    f.write("// Auto-generated by export.py -- do not edit by hand\n")
    f.write("#ifndef MODEL_DATA_H\n#define MODEL_DATA_H\n\n")
    f.write("#include <stdint.h>\n\n")
    f.write(f"#define FIXED_SHIFT {SHIFT}\n")
    f.write(f"#define INPUT_SIZE {INPUT_SIZE}\n")
    f.write(f"#define HIDDEN_SIZE {HIDDEN_SIZE}\n")
    f.write(f"#define OUTPUT_SIZE {OUTPUT_SIZE}\n")
    f.write(f"#define NUM_TEST_IMAGES {len(chosen_images)}\n\n")
    f.write(c_array("weights1", W1_fx) + "\n")   # INPUT_SIZE * HIDDEN_SIZE
    f.write(c_array("bias1", b1_fx) + "\n")       # HIDDEN_SIZE
    f.write(c_array("weights2", W2_fx) + "\n")   # HIDDEN_SIZE * OUTPUT_SIZE
    f.write(c_array("bias2", b2_fx) + "\n")       # OUTPUT_SIZE
    f.write(c_array("test_images", chosen_images) + "\n")  # NUM_TEST_IMAGES * INPUT_SIZE
    f.write(c_array("test_labels", chosen_labels) + "\n")  # NUM_TEST_IMAGES
    f.write("#endif\n")

import os
size_kb = os.path.getsize("../userspace/model_data.h") / 1024
print(f"Wrote model_data.h ({size_kb:.1f} KB)")